- hosts: localhost
  connection: local
  roles:
    - { role: homebrew, tags: [homebrew] }
    - { role: anyenv, tags: [anyenv] }
    - { role: gem, tags: [gem] }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: go, tags: [go] }
    - { role: php, tags: [php] }
