- hosts: localhost
  connection: local
  gather_facts: no
  sudo: yes
  vars:
    homebrew_taps:
    homebrew_packages:
    homebrew_cask_packages:
    gem_packages:
        - { name: homesick }
    tasks:
        - name: add homebrew tap repository
          homebrew_tap: tap={{ item }} state=present
          with_items: homebrew_taps

        - name: update homebrew
          homebrew: update_homebrew=yes

        # brew
        - name: install brew packages
          homebrew: >
            name={{ item.name }}
            state={{ item.state | defalt() | join(',') }}
            if item.install_options is not string
            else item.install_options
          with_items: homebrew_packages
          register: brew_result

        - name: make infomation directory of brew packages
          file: path=brew_info state=directory

        - name: save infomation of brew packages
          shell: brew info {{ item }} > brew_info/{{ item }}
          with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

        # cask
        - name: install homebrew-cask
          homebrew: name=brew-cask state=latest

        - name: install cask packages
          homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
          with_items: homebrew_cask_packages
          register: cask_result

        - name: make infomation directory of cask packages
          file: path=cask_info state=directory

        - name: save infomation of cask packages
          shell: brew cask info {{ item }} > cask_info/{{ item }}
          with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

        # gem
        - name: install gem packages
          gem: name={{ item.name }} state={{ item.state|default('installed') }}
          with_items: gem_packages
