---
- hosts: all

  vars:
    user: mal
    home_dir: "/Users/{{ user }}"
    homebrew_install_path: /usr/local
    homebrew_cask_appdir: /Applications
    caskroom_dir: /opt/homebrew-cask/Caskroom
    zsh_path: /usr/local/bin/zsh
    user_lib: "/Users/{{ user }}/Library"
    user_lib_prefs: "{{ user_lib }}/Preferences"
    homebrew_taps:
      - homebrew/dupes
      - caskroom/cask
      - caskroom/versions
    homebrew_cask_apps:
      - firefox
      - google-chrome
      - dash
      - evernote
      - spectacle
      - recordit
      - iterm2
      - quicksilver
      - vagrant
      - virtualbox
      - dropbox
      - osxfuse
      - 0xed
      - 1password
      - adium
      - slack
      - viscosity
      - little-snitch
      - vmware-fusion
      - stellarium
      - torbrowser
      - wunderlist
      - yubico-authenticator
      - yubikey-personalization-gui
      - dockertoolbox
      - yara
      - thunderbird
      - microsoft-office
      - handbrake

    homebrew_installed_apps:
      - caskroom/cask/brew-cask
      - zsh
      - zsh-completions
      - wget
      - htop
      - tmux
      - git
      - git-flow
      - go
      - hub
      - macvim
      - python3
      - coreutils
      - ctags
      - autoconf
      - automake
      - gcc
      - binutils
      - openssl
      - pinentry
      - libdvdcss

  tasks:
      - include: tasks/dotfiles.yml tags=dotfiles
      - include: tasks/homebrew.yml tags=homebrew
      - include: tasks/osx.yml tags=osx
