linked_packages:
  - { name: openssl }
  - { name: libxml2 }
  - { name: mcrypt }
  - { name: autoconf }
  - { name: automake }
  - { name: bison }
  - { name: libjpeg }
  - { name: libpng }
php_version: 7.0.2
