- name: install homebrew-cask
  homebrew: name=brew-cask state=latest

- name: install cask packages
  homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
  with_items:
    - "{{ homebrew_cask_packages }}"
  register: cask_result

- name: make infomation directory of cask packages
  file: path=cask_info state=directory

- name: save infomation of cask packages
  shell: brew cask info {{ item }} > cask_info/{{ item }}
  with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
