 - name: Ensure dotfiles repository
   git:
     repo: "{{ dotfiles_repo }}"
     dest: "{{ dotfiles_repo_local_destination }}"
     accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
   become: no

 - name: Ensure all configured dotfiles are links
   shell: "ls -F {{ dotfiles_home }}/{{ item }}"
   register: existing_dotfile_info
   with_items: "{{ dotfiles_files }}"

 - name: Link dotfiles into home folder
   file:
     src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
     dest: "{{ dotfiles_home }}/{{ item }}"
     state: link
   become: no
   with_items: "{{ dotfiles_files }}"