 - name: Install osx defaluts settings
   osx_defaults:
     domain: "{{ item.domain }}"
     key: "{{ item.key }}"
     type: "{{ item.type }}"
     value: "{{ item.value }}"
     state: "{{ item.state }}"
   with_items:
    - "{{ osx_defaults }}"

 - name: Killall system setting
   shell: killall {{ item.name }}
   with_items:
    - "{{ killall }}"