 - name: Linked homebrew packages to use phpenv
   homebrew:
    name={{ item.name }}
    state=linked
   with_items:
    - "{{ linked_packages }}"

 - name: Install php to use phpenv
   shell: phpenv install {{ php_version }}
   register: install_phpenv
   changed_when: install_phpenv.rc != 0

 - name: Write the version to use phpenv
   shell: phpenv global {{ php_version }}
   register: global_phpenv
   changed_when: global_phpenv.rc != 0

 - name: Check composer
   stat: path=/usr/local/bin/composer
   register: composer_bin

 - block:
   - name: Download composer
     get_url:
       url: https://getcomposer.org/installer
       dest: /tmp/installer

   - name: install composer
     shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin

   - name: rename composer.phar to composer
     shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer

   - name: make composer executable
     file:
       path: /usr/local/bin/composer
       mode: a+x
       state: file
   when: not composer_bin.stat.exists
